spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=${JWT_SECRET:mySecretKey2024EduMSApplicationJWT256bitsLong}
app.jwt.expiration=900000
app.refresh-token.duration-days=7
server.port=${PORT:8080}
