server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
spring.datasource.username=yerasyl
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
jwt.secret=EduMSSecretKey2024VeryLongSecretKeyThatIsAtLeast256BitsLong!!
jwt.expiration=900000
jwt.refresh-expiration=604800000
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.jackson.deserialization.fail-on-unknown-properties=false
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
